# Generated by Django 4.2.3 on 2023-07-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula1Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('driver1', models.CharField(max_length=30)),
                ('driver2', models.CharField(max_length=30)),
                ('car', models.CharField(max_length=30)),
            ],
        ),
    ]
