# Generated by Django 4.2.2 on 2023-07-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula1teams',
            name='car',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formula1teams',
            name='country',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formula1teams',
            name='driver1',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formula1teams',
            name='driver2',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='formula1teams',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
